import { RenderRequest } from "@storyforge/llm-client";
import { WorldState, NarrativeState } from "@storyforge/simulation-engine";

import { DeterministicExpansionService } from "./DeterministicExpansionService";
import { EmotionGuidance } from "./EmotionTrendService";

import { StoryNode } from "../models/StoryNode";
import { AdventureCharacter } from "../models/Adventure";
import { neutralEmotionProfile } from "../models/EmotionProfile";

export interface InitialStoryInput {

    adventureId: string;

    worldState: WorldState;

    characters: AdventureCharacter[];

    actorName: string;

    ageRange: string;

    aboutChild?: string;

    domain: string;

    skillFocus: string[];

    location: string;

    premise: string;

}

export interface InitialStoryResult {

    rootNode: StoryNode;

    nodes: StoryNode[];

    // Phase 2A: the seeded persistent story state -- derived here
    // (not by a Gemini call) since this class already receives every
    // input needed (premise/characters/location/skillFocus).
    // AdventureRuntime.startAdventure() persists this onto the real
    // WorldState.
    narrativeState: NarrativeState;

}

const ROOT_NODE_ID = "root";

// Correction pass (Sections 2, 3, 6): builds ONLY the minimum graph
// structure needed to start valid gameplay -- root + up to 4
// frontier nodes -- by composing the SAME deterministic pipeline
// (CandidateEventGenerator -> ConstraintEngine -> EventScorer) that
// DeterministicExpansionService already uses for ongoing expansion.
export class InitialStoryBuilder {

    constructor(
        private readonly deterministicExpansionService: DeterministicExpansionService
    ) {}

    async build(
        input: InitialStoryInput
    ): Promise<InitialStoryResult> {

        const narrativeState = this.seedNarrativeState(input);

        const emotionGuidance: EmotionGuidance = {

            shouldReduceDifficulty: false,

            shouldIncreaseEncouragement: false,

            promptNote: "No emotional history yet -- this is the opening of the adventure."

        };

        const expansion = await this.deterministicExpansionService.expand({

            adventureId: input.adventureId,

            worldState: input.worldState,

            characters: input.characters,

            actorName: input.actorName,

            ageRange: input.ageRange,

            aboutChild: input.aboutChild,

            domain: input.domain,

            skillFocus: input.skillFocus,

            recentEventTypes: [],

            recentEvents: [],

            emotionGuidance,

            turn: 0,

            endingEligible: false,

            narrativeState,

            nodeIdPrefix: "frontier"

        });

        const rootRenderRequest: RenderRequest = {

            ageRange: input.ageRange,

            tone: "fantasy_adventure",

            maxSentences: 3,

            location: input.location,

            actorName: input.actorName,

            eventType: "adventure_opening",

            narrativeSeed: input.premise,

            personalizationHint: input.aboutChild,

            complexity: "rich"

        };

        const rootNode: StoryNode = {

            id: ROOT_NODE_ID,

            adventureId: input.adventureId,

            narrative: "",

            pendingRenderRequest: rootRenderRequest,

            choices: expansion.entryChoices,

            learningSignals: [],

            emotion: neutralEmotionProfile(),

            effects: [],

            difficulty: 1,

            readingLevel: input.ageRange,

            isEnding: false,

            createdAt: new Date().toISOString()

        };

        return { rootNode, nodes: expansion.nodes, narrativeState };

    }

    // Phase 2A (Section 4): derived conservatively from already-
    // available metadata -- no new Gemini call, no fabricated
    // precision. If metadata genuinely doesn't support a field
    // (e.g. no characters at all), that field stays empty/undefined
    // rather than inventing content.
    private seedNarrativeState(
        input: InitialStoryInput
    ): NarrativeState {

        return {

            location: input.location,

            // Conservative: only the FIRST character is established
            // at the opening -- not "every character in the
            // adventure's metadata is somehow already present."
            activeCharacterIds: input.characters[0] ? [input.characters[0].id] : [],

            // Derived from the existing learningPlan field (already
            // generated by AdventureMetadataGenerator) rather than
            // inventing a new one.
            currentGoal: input.skillFocus[0]
                ? `find a way through what's happening, learning something about ${input.skillFocus[0]} along the way`
                : "find a way through what's happening",

            // The opening premise IS the initial established problem
            // -- it's what the child arrives to find.
            currentProblem: input.premise,

            establishedFacts: [input.premise],

            unresolvedThreads: [],

            recentEventTypes: []

        };

    }

}
